version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres_desafio_dev
    restart: always
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: 9dPaB2u6Z%&A7#%
      POSTGRES_DB: desafio_dev
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    driver: local