// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package postgres

import (
	"time"
)

type Transaction struct {
	ID     int32     `json:"id"`
	Type   string    `json:"type"`
	Date   time.Time `json:"date"`
	Value  float64   `json:"value"`
	Cpf    string    `json:"cpf"`
	Card   string    `json:"card"`
	Time   time.Time `json:"time"`
	Owner  string    `json:"owner"`
	Market string    `json:"market"`
}
