// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package postgres

import (
	"context"
)

type Querier interface {
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error)
	GetTransaction(ctx context.Context, id int32) (GetTransactionRow, error)
	ListMarketTransaction(ctx context.Context, market string) ([]ListMarketTransactionRow, error)
	ListMarkets(ctx context.Context) ([]string, error)
	MarketBalance(ctx context.Context, market string) (float64, error)
}

var _ Querier = (*Queries)(nil)
