// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Carlos",
            "url": "https://github.com/suportebeloj",
            "email": "carlos.e.alves2@proton.me"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/detail/{market}": {
            "get": {
                "description": "return a json contains information about the store and your transactions",
                "consumes": [
                    "text/plain; charset=utf-8"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Market Detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "market name",
                        "name": "market",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/markets": {
            "get": {
                "description": "return a json contains a list of string representing the registered stores",
                "consumes": [
                    "text/plain; charset=utf-8"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "List Registered stores",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/new": {
            "post": {
                "description": "upload a CNAB file to save the transactions on database",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "text/plain; charset=utf-8"
                ],
                "summary": "Create a Transaction",
                "parameters": [
                    {
                        "type": "file",
                        "description": "CNAB file",
                        "name": "transactions",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Swagger Desafio Dev",
	Description:      "Test server for dev challenge.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
